theme: jekyll-theme-cayman
title: Fashion Outfit Recommendation by Leveraging Visual Styles
description: As Part of Master Thesis of Fatemeh Nazary supervised by Prof. Albanaese, Univerity of Pavia, Sep 2019
